spring:
  application:
    name: Blog-Management

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 29600
    username: postgres
    url:  jdbc:postgresql://localhost:5432/Blog-Management


  jpa:
    properties:
      hibernate:
        format_sql:  true
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/Blog-Management
server:
  port: 8082
